language: node_js

node_js:
  - "12"
  - "10"

cache: yarn

sudo: false

notifications:
  email: false

before_script:
  - npm prune

script:
  - yarn test:coverage
  - yarn build
  - yarn danger ci

after_success:
  - npx codecov
