language: node_js

node_js:
  - "10"
  - "8"

cache:
  directories:
    - node_modules

sudo: false

notifications:
  email: false

before_script:
  - npm prune

script:
  - npm run danger ci

after_success:
  - npx codecov
